/**
 * Build "read more" links for individual matches.
 *
 * Strategy:
 * - Wikipedia: direct article URLs from the pre-built match-links.json
 *   mapping when available, falling back to the tournament page.
 * - FIFA: match centre URLs from the pre-built mapping when available,
 *   falling back to a FIFA search URL.
 *
 * The match-links.json file is generated by `scripts/build-links.ts`
 * which scrapes Wikipedia wikitext for FIFA match centre URLs and maps
 * stages to direct Wikipedia article pages.
 */

import type { Match } from "./types";
import matchLinksData from "../../data/match-links.json";

const WIKIPEDIA_BASE = "https://en.wikipedia.org";
const FIFA_BASE = "https://www.fifa.com";

interface MatchLinkEntry {
  wikipedia: string;
  fifa?: string;
}

const matchLinks: Record<string, MatchLinkEntry> = matchLinksData as Record<
  string,
  MatchLinkEntry
>;

function getYear(match: Match): string {
  return match.tournament.replace(" FIFA Men's World Cup", "").trim();
}

function matchKey(match: Match): string {
  return `${match.date}|${match.homeTeam}|${match.awayTeam}`;
}

/**
 * Returns a direct Wikipedia article URL for a given match.
 *
 * Uses the pre-built mapping from match-links.json which maps each match
 * to its most specific Wikipedia article (final, knockout stage, etc.).
 * Falls back to the main tournament article if no mapping exists.
 */
export function getWikipediaUrl(match: Match): string {
  const key = matchKey(match);
  const entry = matchLinks[key];

  if (entry?.wikipedia) {
    return entry.wikipedia;
  }

  // Fallback: link to the main tournament page
  const year = getYear(match);
  return `${WIKIPEDIA_BASE}/wiki/${year}_FIFA_World_Cup`;
}

/**
 * Returns a FIFA match centre URL if available from the pre-built mapping,
 * otherwise returns a FIFA search URL as a fallback.
 */
export function getFifaUrl(match: Match): string {
  const key = matchKey(match);
  const entry = matchLinks[key];

  if (entry?.fifa) {
    return entry.fifa;
  }

  // Fallback: FIFA search
  const year = getYear(match);
  const query = `${match.homeTeam} ${match.awayTeam} ${year} World Cup`;
  return `${FIFA_BASE}/en/search#q=${encodeURIComponent(query)}`;
}

/**
 * @deprecated Use getFifaUrl instead. Kept for backward compatibility.
 */
export const getEspnSearchUrl = getFifaUrl;
